version: '3'

tasks:
  config:
    cmds:
      - sudo cp s1/etc/mysql/mysql.conf.d/mysqld.cnf /etc/mysql/mysql.conf.d/mysqld.cnf
      - sudo cp s1/etc/nginx/nginx.conf /etc/nginx/nginx.conf
      - sudo cp s1/etc/nginx/sites-available/isucari.conf /etc/nginx/sites-available/isucari.conf
      - sudo nginx -t
      - sudo systemctl reload nginx
      - sudo systemctl restart mysql

  bench:
    cmds:
      - cd ~/isucari && git pull
      - cd ~/isucari/webapp/go && make isucari && sudo systemctl restart isucari.golang.service
      - sudo systemctl restart mysql
      - sudo nginx -t && sudo systemctl reload nginx

  log:
    cmds:
      - sudo pt-query-digest --filter 'length($$event->{arg}) <= 4000' /var/log/mysql/mysql-slow.log > ~/isucari/log/$(date +mysql-slow.log-%m-%d-%H-%M -d "+9 hours") && sudo rm /var/log/mysql/mysql-slow.log
      - sudo cat /var/log/nginx/access.log | alp ltsv -m "/users/\d+.json","/items/\d+.json","/new_items/\d+.json","/upload/.+.jpg","/transactions/\d+.png" --sort sum -r > ~/isucari/log/$(date +access.log-%m-%d-%H-%M -d "+9 hours") && sudo rm /var/log/nginx/access.log
